config/routes.rb
Rails.application.routes.draw do
  get 'signin' => 'sessions#new'
  get 'signout' => 'sessions#destroy'
  get 'signup' => 'users#new'

  root 'blogs#index'

  resources :users do
  	resources :blogs do
  	end
  end

  resources :blogs do
    resources :comments do
    end
  end

  resources :sessions

  resources :my_blogs, only: [:index]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
  belongs_to :user
  has_many :comments

  validates :title, presence: true
  validates :content, presence: true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :blog
  belongs_to :user

  validates :content, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  before_create :downcase_fields

	has_secure_password

  has_many :blogs

  private
    def downcase_fields
      self[:email].downcase!
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user

  private
  	def current_user
  		@current_user ||= User.find(session[:user_id]) if session[:user_id]
  	end
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  def index
    top_num = 10
    @top_commented_blogs = top_commented(top_num)
    @top_recent_blogs = top_recent(top_num)
  end

  def new
    @user = User.find(params[:user_id])
    @blog = @user.blogs.new
  end

  def create
    @user = User.find(params[:user_id])
    @blog = @user.blogs.new(blog_params)
    if @blog.save
      flash[:success] = "Create new blog successfully"
      redirect_to root_path
    else
      flash.now[:notice] = @blog.errors.full_messages.to_sentence
      render 'new'
    end
  end

  def update
    @blog = Blog.find(params[:id])
    @blog.update(blog_params)
    flash[:success] = "Update success"
    redirect_to user_blog_path(@blog.user, @blog)
  end

  def edit
    @user = User.find(params[:user_id])
    @blog = @user.blogs.where("id = ?", params[:id]).first
  end

  def show
    @blog = Blog.find(params[:id])
    @comments = @blog.comments.order(created_at: :desc)
    @comment = @blog.comments.new
  rescue ActiveRecord::RecordNotFound
    flash[:notice] = "Blog not found"
    redirect_to root_path
  end

  private
    def blog_params
      params.require(:blog).permit(:title, :content)
    end

    def top_commented(top_num)
      Blog.all.select("blogs.*, COUNT(1) as comment_count").joins("JOIN comments as comments ON comments.blog_id = blogs.id").group("id").order("comment_count DESC").limit(top_num)

    end

    def top_recent(top_num)
      Blog.order(created_at: :desc).limit(top_num)
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @blog = Blog.find(params[:blog_id])
    @comment = @blog.comments.new(comment_params)
    if @comment.save
      flash[:success] = "Add new comment successfully"
      redirect_to blog_path(@blog)
    else
      flash[:notice] = @comment.errors.full_messages.to_sentence
      redirect_to blog_path(@blog)
    end
  end

  private
    def comment_params
      params.require(:comment).permit(:content, :user_id)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    @blogs = Blog.all
  end
end

app/controllers/my_blogs_controller.rb
class MyBlogsController < ApplicationController
  def index
    @blogs = current_user.blogs.order(created_at: :desc)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = UserLogin.new.login(params[:email], params[:password])
    if user
      session[:user_id] = user.id
      flash[:success] = "Welcome back !"
      redirect_to root_path
    else
      flash.now[:notice] = "Email or password is incorrect"
      render 'new'
    end
  end

  def index
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end
end

app/controllers/sessions_controller/user_login.rb
class SessionsController
  class UserLogin
    def login(email, password)
      user = User.find_by(email: email.downcase)
      user if user.try(:authenticate, password)
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_path
    else
      flash[:notice] = @user.errors.full_messages.to_sentence
      render 'new'
    end
  end

  private
    def user_params
      params.require(:user).permit(:email, :name, :password)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def bootstrap_class_for flash_type
    { success: 'alert-success', error: 'alert-danger', notice: 'alert-warning' }[flash_type.to_sym]
  end

  def flash_messages(opts = {})
    flash.map do |type, message|
      content_tag(:div, message, class: "alert #{bootstrap_class_for(type)} fad in") do
        content_tag(:button, 'x'.html_safe, class: 'close', data: {dismiss: 'alert'}) + message
      end
    end.join.html_safe
  end

  def format(time)
    time.strftime("%H:%M %d-%m-%Y")
  end
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/my_blogs_helper.rb
module MyBlogsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/blogs/_blog.html.erb
<div class="blog">
  <div class="row">
    <div class="col-xs-9">
      <div class="blog-head">
        <h4 class="blog-title">
          <%= link_to blog_path(blog) do %>
            <%= blog.title %>
          <% end %>
        </h4>
        <p class="author">By <%= blog.user.name %></p>
        <p class="blog-content-summary"><%= blog.content[0..300].gsub(/\s\w+\s*$/,'...') %></p>
      </div>
    </div>
    <div class="col-xs-3">
      <div class="blog-head">
        <div class="published-date"><span class="po-date"><%= blog.created_at.strftime("%b") %></span><%= blog.created_at.strftime("%e, %Y") %></div>
        <%= link_to blog_path(blog) do %>
          <div class="comments-link">
            <%= blog.comments.count %><i class="fa fa-comment-o fa-lg" style="display: block;" aria-hidden="true"></i>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/blogs/_comment.html.erb
<div class="comment-content-wrap">
  <div class="card">
    <div class="card-block">
      <h5 class="card-title"><%= comment.user.name %> <span class="pull-xs-right time"><%= format(comment.created_at) %></span></h5>
      <p class="card-text"><%= comment.content %></p>
    </div>
  </div>
</div>

app/views/blogs/_form.html.erb
<%= form_for [current_user, blog] do |f| %>
  <fieldset class="form-group">
    <%= f.label :title, "Title" %>
    <%= f.text_field :title, class: "form-control", placeholder: "" %>
  </fieldset>
  <fieldset class="form-group">
    <%= f.label :content, "Content" %>
    <%= f.text_area :content, class: "form-control", placeholder: "", rows: 10 %>
  </fieldset>
  <%= f.submit "Save", class: "btn btn-primary" %>
<% end %>

app/views/blogs/create.html.erb
<h1>Blogs#create</h1>
<p>Find me in app/views/blogs/create.html.erb</p>

app/views/blogs/edit.html.erb
<h1>Edit blog</h1>
<%= render partial: 'form', locals: {blog: @blog} %>

app/views/blogs/index.html.erb
<div class="blogs">
  <div class="row">
    <div class="col-sm-12">
      <h3>Most commented blogs</h3>
      <% @top_commented_blogs.each do |blog| %>
        <%= render partial: 'blog', locals: {blog: blog} %>
      <% end %>
    </div>
  </div>
  <div class="row">
    <div class="col-sm-12">
      <h3>Most recent blogs</h3>
      <% @top_recent_blogs.each do |blog| %>
        <%= render partial: 'blog', locals: {blog: blog} %>
      <% end %>
    </div>
  </div>
</div>

app/views/blogs/new.html.erb
<h1>New blog</h1>
<%= render partial: 'form', locals: {blog: @blog} %>

app/views/blogs/show.html.erb
<div class="blog">
  <div class="row blog-container">
    <div class="col-sm-12">
      <h3 class="blog-title"><%= @blog.title %>
        <% if current_user && current_user.id == @blog.user.id %>
          <%= link_to edit_user_blog_path(current_user, @blog), style: "margin-left: 20px;" do %>
            <i class="fa fa-pencil" aria-hidden="true"></i>
          <% end %>
        <% end %>
      </h3>
      <p class="author">By <%= @blog.user.name %><span> at <%= format(@blog.created_at) %></span></p>
      <p><%= @blog.content %></p>
    </div>
  </div>
  <div class="row">
    <div class="col-sm-4 new-comment">
      <h4>Add new comment</h4>
      <% if current_user %>
        <%= form_for [@blog, @comment] do |f| %>
          <fieldset class="form-group">
            <%= f.hidden_field :user_id, value: current_user.id %>
          </fieldset>
          <fieldset class="form-group">
            <%= f.text_field :content, class: "form-control", placeholder: "Your comment content ..." %>
          </fieldset>
          <%= f.submit "Add", class: "btn btn-primary" %>
        <% end %>
      <% else %>
        <%= link_to "Sign in", signin_path %> or <%= link_to "Sign up", signup_path %> to comment
      <% end %>
    </div>
    <div class="col-sm-8 comments">
      <h4>Comments (<%= @comments.size %>)</h4>
      <div class="comments-list">
        <% @comments.each do |comment| %>
          <%= render partial: "comment", locals: {comment: comment} %>
        <% end %>
      </div>
    </div>
  </div>
  <!-- <div class="row">
    <div class="col-sm-12 new-comment">
      <h4>Add new comment</h4>
      <%= form_for [@blog, @comment] do |f| %>
        <fieldset class="form-group">
          <%= f.text_field :content, class: "form-control", placeholder: "Your comment content ..." %>
        </fieldset>
        <%= f.submit "Add", class: "btn btn-primary" %>
      <% end %>
    </div>
  </div> -->
</div>

app/views/blogs/update.html.erb
<h1>Blogs#update</h1>
<p>Find me in app/views/blogs/update.html.erb</p>

app/views/comments/create.html.erb
<h1>Comments#create</h1>
<p>Find me in app/views/comments/create.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Robust Blog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-fixed-top navbar-custom">
      <a href="<%= root_path %>" class="navbar-brand">Robust Blog</a>
      <ul class="nav navbar-nav">
        <li class="nav-item">
          <%= link_to "Home", root_path, class: "nav-link" %>
        </li>
        <% unless current_user %>
          <li class="nav-item">
            <%= link_to "Sign in", signin_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Sign up", signup_path, class: "nav-link" %>
          </li>
        <% end %>
        <% if current_user %>
          <li class="nav-item">
            <%= link_to "My blogs", my_blogs_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to new_user_blog_path(current_user), class: "nav-link btn btn-default" do %>
              <i class="fa fa-plus fa-lg" aria-hidden="true"></i> New blog
            <% end %>
          </li>
          <div class="pull-xs-right">
            <div class="btn-group">
              <button class="btn btn-secondary dropdown-toggle" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <%= current_user.name %>
              </button>
              <div class="dropdown-menu">
                <%= link_to "Logout", "/signout", class: "dropdown-item" %>
              </div>
            </div>
          </div>
        <% end %>
      </ul>
    </nav>

    <div class="container pad-top-70">
      <%= flash_messages %>
      <%= yield %>
    </div>

  </body>
</html>

app/views/my_blogs/index.html.erb
<div class="blogs">
  <div class="row">
    <div class="col-sm-12">
      <h3>Your blogs</h3>
      <% if @blogs.size == 0 %>
        <p>You don't have any blog. Create <%= link_to "new one", new_user_blog_path(current_user) %></p>
      <% else %>
        <% @blogs.each do |blog| %>
          <%= render partial: 'blogs/blog', locals: {blog: blog} %>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/users/_sign_up.html.erb
<div class="card">
  <div class="card-block">
    <h3 class="card-title">Sign up new account</h3>
    <div class="card-text">
      <%= form_for @user do |user| %>
        <fieldset class="form-group">
          <%= user.label :name, "Name" %>
          <%= user.text_field :name, class: "form-control", placeholder: "" %>
        </fieldset>
        <fieldset class="form-group">
          <%= user.label :email, "Email" %>
          <%= user.email_field :email, class: "form-control", placeholder: "" %>
        </fieldset>
        <fieldset class="form-group">
          <%= user.label :password, "Password" %>
          <%= user.password_field :password, class: "form-control" %>
        </fieldset>
        <%= user.submit "Sign up", class: "btn btn-primary-outline" %>
        <%= link_to "Already have account", "/login", style: "margin-left: 20px" %>
      <% end %>
    </div>
  </div>
</div>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/new.html.erb
<div class="users">
  <%= render partial: "sign_up" %>
</div>